# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"\xa1\x01\n\x05Order\x12\x17\n\nproduct_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08quantity\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05price\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12 \n\toperation\x18\x04 \x01(\x0e\x32\x08.OrderOpH\x03\x88\x01\x01\x42\r\n\x0b_product_idB\x0b\n\t_quantityB\x08\n\x06_priceB\x0c\n\n_operation*6\n\x07OrderOp\x12\r\n\tOrdCREATE\x10\x00\x12\r\n\tOrdUPDATE\x10\x01\x12\r\n\tOrdDELETE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDEROP']._serialized_start=179
  _globals['_ORDEROP']._serialized_end=233
  _globals['_ORDER']._serialized_start=16
  _globals['_ORDER']._serialized_end=177
# @@protoc_insertion_point(module_scope)
