# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"\xf3\x01\n\tInventory\x12\x17\n\nproduct_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08\x63\x61tegory\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05price\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12(\n\toperation\x18\x06 \x01(\x0e\x32\x10.InventoryOpTypeH\x05\x88\x01\x01\x42\r\n\x0b_product_idB\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x0b\n\t_categoryB\x08\n\x06_priceB\x0c\n\n_operation*>\n\x0fInventoryOpType\x12\r\n\tInvCREATE\x10\x00\x12\r\n\tInvUPDATE\x10\x01\x12\r\n\tInvDELETE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTORYOPTYPE']._serialized_start=265
  _globals['_INVENTORYOPTYPE']._serialized_end=327
  _globals['_INVENTORY']._serialized_start=20
  _globals['_INVENTORY']._serialized_end=263
# @@protoc_insertion_point(module_scope)
